name: make

on: workflow_dispatch

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run make -- --platform=linux --arch=x64 --targets=@electron-forge/maker-zip
      - uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: out/make/zip/linux/x64/bruno-pdf-*.zip

  win64:
    name: Windows (x64)
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run make -- --platform=win32 --arch=x64 --targets=@electron-forge/maker-zip
      - uses: actions/upload-artifact@v4
        with:
          name: win32-x64
          path: out/make/zip/win32/x64/bruno-pdf-*.zip
